name: IsmailWorxVPN
options:
  bundleIdPrefix: com.yourcompany
targets:
  IsmailWorxVPN:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - path: vpn-ios-files
        excludes: ["**/CMakeLists.txt"]
      - path: src/Cedar
        excludes: ["**/CMakeLists.txt"]
      - path: src/Mayaqua
        excludes: ["**/CMakeLists.txt"]
    info:
      path: vpn-ios-files/Info.plist
    settings:
      base:
        SWIFT_OBJC_BRIDGING_HEADER: "$(SRCROOT)/vpn-ios-files/TestApp-Bridging-Header.h"
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: ""
        PROVISIONING_PROFILE_SPECIFIER: ""
        HEADER_SEARCH_PATHS: "$(SRCROOT)/vpn-ios-files $(SRCROOT)/src $(SRCROOT)/src/Cedar $(SRCROOT)/src/Mayaqua"