name: IsmailWorxVPN
options:
  bundleIdPrefix: com.yourcompany

targets:
  IsmailWorxVPN:
    type: application
    platform: iOS
    deploymentTarget: "13.0"
    sources:
      - path: vpn-ios-files
        excludes:
          - "**/CMakeLists.txt"
          - "vpnbridge.c"
      - path: src/Cedar
        excludes:
          - "**/CMakeLists.txt"
          - "**/Win*.c"
          - "**/Win*.cpp"
          - "**/Win*.h"
          - "Virtual.c"
          - "VLanWin32.c"
          - "Server.c"
          - "Session.c"
          - "SecureNAT.c"
          - "Sam.c"
          - "Radius.c"
          - "Proto_WireGuard.c"
          - "Proto_IKE.c"
          - "Proto_EtherIP.c"
          - "Proto_IPsec.c"
          - "NullLan.c"
      - path: src/Mayaqua
        excludes:
          - "**/CMakeLists.txt"
          - "Tick64.c"
          - "Table.c"
          - "Secure.c"
          - "Network.c"
          - "OS.c"
    info:
      path: vpn-ios-files/Info.plist
    settings:
      base:
        GCC_TREAT_WARNINGS_AS_ERRORS: NO
        CLANG_TREAT_WARNINGS_AS_ERRORS: NO
        SWIFT_TREAT_WARNINGS_AS_ERRORS: NO
        SWIFT_OBJC_BRIDGING_HEADER: "$(SRCROOT)/vpn-ios-files/TestApp-Bridging-Header.h"
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: "-"
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: ""
        PROVISIONING_PROFILE_SPECIFIER: ""
        PROVISIONING_PROFILE: ""
        HEADER_SEARCH_PATHS: |
          $(SRCROOT)/vpn-ios-files
          $(SRCROOT)/src
          $(SRCROOT)/src/Cedar
          $(SRCROOT)/src/Mayaqua
          $(SRCROOT)/external/openssl/include
          $(SRCROOT)/external/openssl/include/openssl
          $(SRCROOT)/external/libsodium/include
          $(SRCROOT)/external/libsodium/include/sodium
        LIBRARY_SEARCH_PATHS: |
          $(SRCROOT)/external/openssl/lib
          $(SRCROOT)/external/libsodium/lib
        OTHER_LDFLAGS: -lssl -lcrypto -lsodium