name: CI - XcodeGen Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode project
        run: xcodegen

      - name: Build the app
        run: |
          xcodebuild -project IsmailWorxVPN.xcodeproj -scheme IsmailWorxVPN -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 14' build