name: iOS CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build libsodium for iOS
        run: |
          git clone https://github.com/jedisct1/libsodium.git
          cd libsodium
          ./dist-build/ios.sh
          mkdir -p $GITHUB_WORKSPACE/external/libsodium
          cp -r libsodium-ios/include $GITHUB_WORKSPACE/external/libsodium/
          cp -r libsodium-ios/lib $GITHUB_WORKSPACE/external/libsodium/

      # Add more build/test steps here as needed