name: iOS CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build and test (SPM)
        run: |
          xcodebuild test \
            -scheme "YOUR_SCHEME" \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=17.4' \
            -sdk iphonesimulator \
            -enableCodeCoverage YES