name: iOS CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download prebuilt libsodium for iOS
        run: |
          curl -L -o libsodium-ios.tar.gz https://github.com/LeoneBacci/libsodium-ios/releases/download/1.0.19/libsodium-ios-1.0.19.tar.gz
          mkdir -p external/libsodium
          tar -xzf libsodium-ios.tar.gz -C external/libsodium --strip-components=1