name: Build iOS App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install XcodeGen
      run: brew install xcodegen

    - name: Set up libsodium
      run: bash scripts/setup-libsodium.sh

    - name: Generate Xcode project
      run: xcodegen

    - name: Build (Debug)
      run: |
        xcodebuild -project IsmailWorxVPN.xcodeproj \
        -scheme IsmailWorxVPN \
        -sdk iphoneos \
        -configuration Debug \
        build