name: iOS CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download and extract libsodium iOS XCFramework
        run: |
          curl -L -o libsodium-ios-xcframework.zip https://github.com/jedisct1/libsodium/releases/download/1.0.19/libsodium-1.0.19-ios-xcframework.zip
          mkdir -p external/libsodium
          unzip libsodium-ios-xcframework.zip -d external/libsodium

      # Add your build steps here! For example:
      # - name: Build your iOS app
      #   run: xcodebuild ...