name: iOS CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build libsodium for iOS
        run: |
          mkdir -p scripts
          wget -O scripts/build-libsodium-ios.sh https://raw.githubusercontent.com/${{ github.repository }}/main/scripts/build-libsodium-ios.sh || true
          chmod +x scripts/build-libsodium-ios.sh
          ./scripts/build-libsodium-ios.sh
          
      # Add your build/test steps here
      # - name: Build your iOS app
      #   run: xcodebuild ... (your build commands)